name: foodlink_admin_panel
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: "3.27.1"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  get: ^4.6.6
  provider: ^6.1.2

  # Storage
  shared_preferences: ^2.3.4

  # Utils
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  image_compression: ^1.0.5
  file_picker: ^8.1.7
  image_picker_web: ^4.0.0
  html: ^0.15.5
  dotted_border: ^2.1.0

  # Google
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  firebase_app_check: ^0.3.1+7
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - lib/core/utils/intl_ar.json
    - lib/core/utils/intl_en.json

  fonts:
    - family: Salsa
      fonts:
        - asset: assets/fonts/Salsa-Regular.ttf
    - family: MyriadArabic
      fonts:
        - asset: assets/fonts/MyriadArabic-Regular.otf
