name: foodlink_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  provider: ^6.1.2
  google_fonts: ^4.0.3
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.5.1
  shared_preferences: ^2.3.2
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  firebase_app_check: ^0.3.1+6
  path_provider: ^2.1.5
  firebase: ^9.0.3
  image_compression: ^1.0.5
  file_picker: ^8.1.4
  image_picker_web: ^4.0.0
  html: ^0.15.5
  dotted_border: ^2.1.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  flutter_staggered_grid_view: ^0.7.0
  excel: ^4.0.6




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - lib/core/utils/intl_ar.json
    - lib/core/utils/intl_en.json

  fonts:
    - family: Salsa
      fonts:
        - asset: assets/fonts/Salsa-Regular.ttf
    - family: MyriadArabic
      fonts:
        - asset: assets/fonts/MyriadArabic-Regular.otf